import type {
  QualidadeBaseResumo,
  StakeholderDetalheDto,
  StakeholderPorClienteDto,
} from "@/prototipo/dashboard-comercial/types";

export const MOCK_RESUMO: QualidadeBaseResumo = {
  totalStakeholders: 347,
  totalClientes: 23,
  semOrcamento2026: { quantidade: 146, percentual: 42.1 },
  semDesafio2026: { quantidade: 205, percentual: 59.1 },
  cLevelDecisorSemVisita60Dias: { quantidade: 12 },
  orcamentoTotal2026: {
    valorMapeadoReais: 80200000,
    percentualCobertura: 58.0,
  },
  semaforo: {
    ate30Dias: 38,
    de31a60Dias: 24,
    de61a90Dias: 19,
    acima90Dias: 12,
  },
};

export const MOCK_POR_CLIENTE: StakeholderPorClienteDto[] = [
  {
    clienteId: 10,
    nomeCliente: "Bradesco",
    totalStakeholders: 42,
    porNivel: { cLevel: 6, decisor: 11, influenciador: 9, operacional: 8, semClassificacao: 8 },
    orcamentoMapeadoReais: 28400000,
    percentualCobertura: 71.0,
    stakeholdersComOrcamento: 30,
    semDesafio: 15,
    percentualSemDesafio: 35.7,
  },
  {
    clienteId: 11,
    nomeCliente: "Itaú",
    totalStakeholders: 38,
    porNivel: { cLevel: 5, decisor: 9, influenciador: 8, operacional: 7, semClassificacao: 9 },
    orcamentoMapeadoReais: 22100000,
    percentualCobertura: 63.0,
    stakeholdersComOrcamento: 24,
    semDesafio: 16,
    percentualSemDesafio: 42.1,
  },
  {
    clienteId: 12,
    nomeCliente: "Santander",
    totalStakeholders: 31,
    porNivel: { cLevel: 4, decisor: 7, influenciador: 6, operacional: 5, semClassificacao: 9 },
    orcamentoMapeadoReais: 15700000,
    percentualCobertura: 52.0,
    stakeholdersComOrcamento: 16,
    semDesafio: 19,
    percentualSemDesafio: 61.3,
  },
  {
    clienteId: 13,
    nomeCliente: "B3",
    totalStakeholders: 18,
    porNivel: { cLevel: 2, decisor: 4, influenciador: 3, operacional: 4, semClassificacao: 5 },
    orcamentoMapeadoReais: 9200000,
    percentualCobertura: 39.0,
    stakeholdersComOrcamento: 7,
    semDesafio: 8,
    percentualSemDesafio: 44.4,
  },
  {
    clienteId: 14,
    nomeCliente: "Porto Seguro",
    totalStakeholders: 14,
    porNivel: { cLevel: 1, decisor: 3, influenciador: 2, operacional: 3, semClassificacao: 5 },
    orcamentoMapeadoReais: 4800000,
    percentualCobertura: 29.0,
    stakeholdersComOrcamento: 4,
    semDesafio: 9,
    percentualSemDesafio: 64.3,
  },
];

const baseStakeholders: StakeholderDetalheDto[] = [
  {
    id: 1021,
    nomeColaborador: "João Martins",
    codigoInternoColaborador: "COL-0421",
    empresa: "Bradesco",
    cargo: "Diretor de Infraestrutura",
    nivel: "cLevel",
    diasSemVisita: null,
    orcamento2026: null,
    desafio2026: null,
    dataCriacao: "2024-03-10",
  },
  {
    id: 1022,
    nomeColaborador: "Luciana Souza",
    codigoInternoColaborador: "COL-0422",
    empresa: "Itaú",
    cargo: "Head de Dados",
    nivel: "decisor",
    diasSemVisita: 12,
    orcamento2026: null,
    desafio2026: null,
    dataCriacao: "2024-01-15",
  },
  {
    id: 1023,
    nomeColaborador: "Paulo Garcia",
    codigoInternoColaborador: "COL-0423",
    empresa: "Santander",
    cargo: "Gerente de Projetos",
    nivel: "influenciador",
    diasSemVisita: 5,
    orcamento2026: null,
    desafio2026: null,
    dataCriacao: "2024-05-01",
  },
  {
    id: 1024,
    nomeColaborador: "Tatiana Costa",
    codigoInternoColaborador: "COL-0424",
    empresa: "B3",
    cargo: "Coordenadora de TI",
    nivel: "operacional",
    diasSemVisita: 20,
    orcamento2026: null,
    desafio2026: null,
    dataCriacao: "2023-11-20",
  },
  {
    id: 1025,
    nomeColaborador: "Marcos Ribeiro",
    codigoInternoColaborador: "COL-0425",
    empresa: "Porto Seguro",
    cargo: "Superintendente",
    nivel: "decisor",
    diasSemVisita: 8,
    orcamento2026: null,
    desafio2026: null,
    dataCriacao: "2024-02-28",
  },
];

/** Listas curtas para painéis (protótipo). */
export const MOCK_STAKEHOLDERS_POR_FILTRO: Record<string, StakeholderDetalheDto[]> = {
  semOrcamento: baseStakeholders,
  semVisita60: [
    {
      id: 2001,
      nomeColaborador: "Ricardo Mendes",
      codigoInternoColaborador: "COL-2001",
      empresa: "Bradesco",
      cargo: "VP de Tecnologia",
      nivel: "cLevel",
      diasSemVisita: 94,
      orcamento2026: 1200000,
      desafio2026: "Modernização",
      dataCriacao: "2023-06-01",
    },
    {
      id: 2002,
      nomeColaborador: "Carla Peixoto",
      codigoInternoColaborador: "COL-2002",
      empresa: "Itaú",
      cargo: "Diretora de Operações",
      nivel: "decisor",
      diasSemVisita: 82,
      orcamento2026: 800000,
      desafio2026: "Eficiência",
      dataCriacao: "2023-08-12",
    },
    {
      id: 2003,
      nomeColaborador: "Felipe Santos",
      codigoInternoColaborador: "COL-2003",
      empresa: "Santander",
      cargo: "CTO",
      nivel: "cLevel",
      diasSemVisita: 77,
      orcamento2026: 2000000,
      desafio2026: null,
      dataCriacao: "2023-04-20",
    },
    {
      id: 2004,
      nomeColaborador: "Ana Nakamura",
      codigoInternoColaborador: "COL-2004",
      empresa: "B3",
      cargo: "Head de Infraestrutura",
      nivel: "decisor",
      diasSemVisita: 68,
      orcamento2026: 500000,
      desafio2026: "Risco",
      dataCriacao: "2023-09-01",
    },
  ],
  semaforoVerde: [
    {
      id: 3001,
      nomeColaborador: "Marcos Torres",
      codigoInternoColaborador: "COL-3001",
      empresa: "Bradesco",
      cargo: "CIO",
      nivel: "cLevel",
      diasSemVisita: 3,
      orcamento2026: 1500000,
      desafio2026: "Cloud",
      dataCriacao: "2024-01-10",
    },
    {
      id: 3002,
      nomeColaborador: "Renata Silva",
      codigoInternoColaborador: "COL-3002",
      empresa: "Itaú",
      cargo: "Diretora de Produtos",
      nivel: "decisor",
      diasSemVisita: 7,
      orcamento2026: 900000,
      desafio2026: "Dados",
      dataCriacao: "2024-02-01",
    },
    {
      id: 3003,
      nomeColaborador: "André Lima",
      codigoInternoColaborador: "COL-3003",
      empresa: "Santander",
      cargo: "Head de Segurança",
      nivel: "decisor",
      diasSemVisita: 12,
      orcamento2026: 600000,
      desafio2026: "Segurança",
      dataCriacao: "2023-12-15",
    },
    {
      id: 3004,
      nomeColaborador: "Patricia Vieira",
      codigoInternoColaborador: "COL-3004",
      empresa: "Bradesco",
      cargo: "VP de Operações",
      nivel: "cLevel",
      diasSemVisita: 18,
      orcamento2026: 2200000,
      desafio2026: "Custos",
      dataCriacao: "2023-10-01",
    },
  ],
  semaforoAmbar: [
    {
      id: 3101,
      nomeColaborador: "Daniel Costa",
      codigoInternoColaborador: "COL-3101",
      empresa: "B3",
      cargo: "Diretor de Tecnologia",
      nivel: "cLevel",
      diasSemVisita: 35,
      orcamento2026: 400000,
      desafio2026: null,
      dataCriacao: "2023-07-01",
    },
    {
      id: 3102,
      nomeColaborador: "Laura Mendonça",
      codigoInternoColaborador: "COL-3102",
      empresa: "Itaú",
      cargo: "Head de Inovação",
      nivel: "decisor",
      diasSemVisita: 42,
      orcamento2026: 700000,
      desafio2026: "Inovação",
      dataCriacao: "2023-05-20",
    },
    {
      id: 3103,
      nomeColaborador: "Gustavo Oliveira",
      codigoInternoColaborador: "COL-3103",
      empresa: "Santander",
      cargo: "Diretor de Dados",
      nivel: "decisor",
      diasSemVisita: 51,
      orcamento2026: 300000,
      desafio2026: null,
      dataCriacao: "2023-08-01",
    },
    {
      id: 3104,
      nomeColaborador: "Vanessa Rocha",
      codigoInternoColaborador: "COL-3104",
      empresa: "Porto Seguro",
      cargo: "Head de TI",
      nivel: "decisor",
      diasSemVisita: 58,
      orcamento2026: 250000,
      desafio2026: "Legado",
      dataCriacao: "2023-09-15",
    },
  ],
  semaforoVermelho: [
    {
      id: 3201,
      nomeColaborador: "Ana Nakamura",
      codigoInternoColaborador: "COL-3201",
      empresa: "B3",
      cargo: "Head de Infraestrutura",
      nivel: "decisor",
      diasSemVisita: 68,
      orcamento2026: 100000,
      desafio2026: "Capacidade",
      dataCriacao: "2023-03-01",
    },
    {
      id: 3202,
      nomeColaborador: "Roberto Barros",
      codigoInternoColaborador: "COL-3202",
      empresa: "Bradesco",
      cargo: "Diretor de Canais",
      nivel: "decisor",
      diasSemVisita: 72,
      orcamento2026: 450000,
      desafio2026: null,
      dataCriacao: "2023-02-10",
    },
    {
      id: 3203,
      nomeColaborador: "Felipe Santos",
      codigoInternoColaborador: "COL-3203",
      empresa: "Santander",
      cargo: "CTO",
      nivel: "cLevel",
      diasSemVisita: 77,
      orcamento2026: 2000000,
      desafio2026: null,
      dataCriacao: "2023-04-20",
    },
    {
      id: 3204,
      nomeColaborador: "Carla Peixoto",
      codigoInternoColaborador: "COL-3204",
      empresa: "Itaú",
      cargo: "Diretora de Operações",
      nivel: "decisor",
      diasSemVisita: 82,
      orcamento2026: 800000,
      desafio2026: "Eficiência",
      dataCriacao: "2023-08-12",
    },
  ],
  semaforo90mais: [
    {
      id: 3301,
      nomeColaborador: "Ricardo Mendes",
      codigoInternoColaborador: "COL-3301",
      empresa: "Bradesco",
      cargo: "VP de Tecnologia",
      nivel: "cLevel",
      diasSemVisita: 94,
      orcamento2026: 1200000,
      desafio2026: "Modernização",
      dataCriacao: "2023-06-01",
    },
    {
      id: 3302,
      nomeColaborador: "Helena Ferreira",
      codigoInternoColaborador: "COL-3302",
      empresa: "Santander",
      cargo: "VP Comercial",
      nivel: "cLevel",
      diasSemVisita: 108,
      orcamento2026: null,
      desafio2026: null,
      dataCriacao: "2022-11-01",
    },
    {
      id: 3303,
      nomeColaborador: "Jorge Almeida",
      codigoInternoColaborador: "COL-3303",
      empresa: "Porto Seguro",
      cargo: "CTO",
      nivel: "cLevel",
      diasSemVisita: 124,
      orcamento2026: 600000,
      desafio2026: null,
      dataCriacao: "2022-08-01",
    },
    {
      id: 3304,
      nomeColaborador: "Marina Campos",
      codigoInternoColaborador: "COL-3304",
      empresa: "B3",
      cargo: "Diretora de Risco",
      nivel: "decisor",
      diasSemVisita: 137,
      orcamento2026: 350000,
      desafio2026: "Compliance",
      dataCriacao: "2022-05-15",
    },
  ],
};
